services:
  rng-api:
    image: courselabs/rng-api:21.05
    environment:
      - Logging__LogLevel__Default=Debug
    volumes: 
      - ./scripts:/scripts
    networks:
      app-net: 
        ipv4_address: 10.218.0.10

  rng-web:
    image: courselabs/rng-web:21.05
    environment:
      - Logging__LogLevel__Default=Debug
      - RngApi__Url=http://10.218.0.10/rng
    ports:
      - "8090:80"
    networks:
      - app-net

networks:
  app-net:
    name: courselabs-rng
    ipam:
      driver: default
      config:
        - subnet: 10.218.0.0/16

