services:

  products-db:
    image: hackathon/products-db
    build:
      context: db/postgres

  products-api:
    image: hackathon/products-api
    build:
      context: products-api/java

  stock-api:
    image: hackathon/stock-api
    build:
      context: stock-api/golang

  web:
    image: hackathon/web
    build:
      context: web/dotnet