services:

  products-db:
    image: hackathon/products-db
    ports:
      - "5432:5432"
    networks:
      - app-net

  products-api:
    image: hackathon/products-api
    environment:
      - PRICE_FACTOR=1.5
    ports:
      - "8081:80"
    networks:
      - app-net

  stock-api:
    image: hackathon/stock-api
    ports:
      - "8082:8080"
    networks:
      - app-net
  
  web:
    image: hackathon/web
    environment:
      - Widgetario__Theme=dark
    volumes:
      - ./config/web:/app/config
      - ./logs/web:/logs
    ports:
      - "8080:80"
    networks:
      - app-net

networks:
  app-net: